name: evoAlg
channels:
  - conda-forge
  - local
  - bioconda
  - defaults
dependencies:
  - scoop=0.7.1.1=pyh2d50403_2
  - deap=1.2.2=py27hf8a1672_0
  - backports=1.0=py27_1
  - backports.functools_lru_cache=1.5=py27_1
  - backports_abc=0.5=py27_0
  - blas=1.0=mkl
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py27_0
  - cycler=0.10.0=py27_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py27_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - functools32=3.2.3.2=py27_1
  - futures=3.2.0=py27_0
  - glib=2.56.2=hd408876_0
  - greenlet=0.4.15=py27h7b6447c_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.1=144
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.0.1=py27hf484d3e_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.36=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - matplotlib=2.2.3=py27hb69df0a_0
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py27ha843d7b_0
  - mkl_random=1.0.2=py27hd81dba3_0
  - mpmath=1.1.0=py27_0
  - ncurses=6.1=he6710b0_1
  - networkx=2.2=py27_1
  - numpy=1.15.4=py27h7e9f1db_0
  - numpy-base=1.15.4=py27hde5b4d6_0
  - openssl=1.1.1b=h7b6447c_1
  - pcre=8.42=h439df22_0
  - pip=18.1=py27_0
  - pyparsing=2.3.0=py27_0
  - pyqt=5.9.2=py27h05f1152_2
  - python=2.7.15=h9bab390_6
  - python-dateutil=2.7.5=py27_0
  - pytz=2018.7=py27_0
  - pyzmq=17.1.2=py27h14c3975_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - scipy=1.1.0=py27h7c811a0_2
  - setuptools=40.6.3=py27_0
  - singledispatch=3.4.0.3=py27h9bcb476_0
  - sip=4.19.8=py27hf484d3e_0
  - six=1.12.0=py27_0
  - sqlite=3.26.0=h7b6447c_0
  - subprocess32=3.5.3=py27h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tornado=5.1.1=py27h7b6447c_0
  - wheel=0.32.3=py27_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.2.5=hf484d3e_1
  - zlib=1.2.11=h7b6447c_3
  - powerlaw=1.4.6=py27h39e3cac_0